config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/login', to: 'user/sessions#new'
  post '/login', to: 'user/sessions#create'

  get '/logout', to: 'user/sessions#destroy'

  get '/stage_1', to: 'stages#stage_1'
  get '/stage_2', to: 'stages#stage_2'
  get '/stage_3', to: 'stages#stage_3'
  get '/stage_4', to: 'stages#stage_4'
  get '/stage_5', to: 'stages#stage_5'
  get '/stage_6', to: 'stages#stage_6'
  get '/stage_7', to: 'stages#stage_7'
  get '/stage_8', to: 'stages#stage_8'
  get '/stage_9', to: 'stages#stage_9'
  get '/stage_10', to: 'stages#stage_10'

  # namespace :user do 
  #   resources :agents, :recruiters, only: [:index, :new, :create, :show, :edit, :update]
  # end

  get '/auth/facebook/callback' => 'user/sessions#facebook'

  scope '/user' do 
    resources :agents, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
    resources :recruiters, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
  end 

  resources :candidates, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/agent.rb
class Agent < User
    has_many :candidates, :foreign_key => :agent_id 
    has_many :recruiters, :through => :candidates
    # Agent.new would save to the User table with a type of 'Agent'

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
    before_action :find_agent, only: [:show, :edit, :update]
    skip_before_action :redirect_if_not_authenticated, only: [:new, :create]
    layout "sidebar"
    
    def new
        if user_authenticated 
            redirect_to candidates_path 
        else
            @agent = Agent.new
            render :layout => "application"
        end
    end 

    def create
        @agent = Agent.create(agent_params)

        if @agent.save 
            session[:user_id] = @agent.id 
            redirect_to agent_path(@agent)
        else 
            render '/agents/new', :layout => "application"
        end

    end 

    def show
    end 

    def edit 
    end 

    def update
        @agent.update(agent_params)
        if @agent.save 
            redirect_to agent_path(@agent)
        else 
            render :edit 
        end
    end 

# --------------------------PRIVATE METHODS---------------------------------------

    private 

    def agent_params 
        params.require(:agent).permit(:first_name, :last_name, :phone_number, :email, :password)
    end 

    def find_agent
        @agent = User.find_by(id: session[:user_id])
    end

end

app/controllers/user/agents_controller.rb
class User::AgentsController < ApplicationController
    before_action :find_agent, only: [:index, :show, :edit, :update]
    skip_before_action :redirect_if_not_authenticated, only: [:new, :create]

    
    def index
        @candidates = @agent.candidates
    end
    
    def new
        @agent = Agent.new
    end 

    def create
        @agent = Agent.create(agent_params)

        if @agent.save 
            session[:user_id] = @agent.id 
            redirect_to agent_path(@agent)
        else 
            render 'user/agents/new'
        end

    end 

    def show
    end 

    def edit 
    end 

    def update
        @agent.update(agent_params)
        redirect_to agent_path(@agent)
    end 

# --------------------------PRIVATE METHODS---------------------------------------

    private 

    def agent_params 
        pararms.require(:agent).permit(:first_name, :last_name, :phone_number, :email, :password)
    end 

    def find_agent
        @agent = Agent.find_by(id: params[:id])
    end

end

app/views/agents/edit.html.erb
<div class="col-6 offset-1 mt-5">
    <div class="shadow card mb-5">
        <h5 class="card-header text-center">Edit <%= current_user.first_name %> <%= current_user.last_name %></h5>
        <div class="card-body">
            <p class="card-text">
                <%= render 'partials/agent_form' %>
            </p>
        </div>
    </div>
</div>

app/views/agents/new.html.erb
<div class="col-4 mt-5">
    <div class="shadow card mb-5">
        <h5 class="card-header text-center">Agent Signup</h5>
        <div class="card-body">
            <p class="card-text">
                <%= render 'partials/agent_form' %>
            </p>
            <p class="card-text">
                <%= link_to '/auth/facebook?state=Agent' do %>
                    <button class="btn btn-outline-success btn-block">
                        <i class="fab fa-facebook text-decoration-none"> &nbsp;Signup with Facebook </i> 
                    </button>
                <% end %>
            </p>
        </div>
    </div>
</div>

app/views/agents/show.html.erb
<div class="col-md-4 col-xl-5 offset-md-2 offset-xl-2 align-self-center">
    <div class="shadow card text-center">
        <h5 class="card-header"><%= @agent.first_name %> <%= @agent.last_name %></h5>
        <div class="card-body">
            <p class="card-text">
                Phone: <%= @agent.phone_number %><br>
                Email: <%= @agent.email %>
            </p>
            <%= link_to "Edit Profile", edit_agent_path, :class => "btn btn-primary" %>
        </div>
    </div>
</div>