config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/login', to: 'user/sessions#new'
  post '/login', to: 'user/sessions#create'

  get '/logout', to: 'user/sessions#destroy'

  get '/stage_1', to: 'stages#stage_1'
  get '/stage_2', to: 'stages#stage_2'
  get '/stage_3', to: 'stages#stage_3'
  get '/stage_4', to: 'stages#stage_4'
  get '/stage_5', to: 'stages#stage_5'
  get '/stage_6', to: 'stages#stage_6'
  get '/stage_7', to: 'stages#stage_7'
  get '/stage_8', to: 'stages#stage_8'
  get '/stage_9', to: 'stages#stage_9'
  get '/stage_10', to: 'stages#stage_10'

  # namespace :user do 
  #   resources :agents, :recruiters, only: [:index, :new, :create, :show, :edit, :update]
  # end

  get '/auth/facebook/callback' => 'user/sessions#facebook'

  scope '/user' do 
    resources :agents, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
    resources :recruiters, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
  end 

  resources :candidates, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
    layout "sidebar"

    def stage_1
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_1.order_by_modified
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_1.order_by_modified 
        end
    end

    def stage_2
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_2.order_by_interview
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_2.order_by_interview 
        end
    end

    def stage_3
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_3.order_by_modified
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_3.order_by_modified 
        end
    end

    def stage_4
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_4.order_by_modified
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_4.order_by_modified 
        end
    end

    def stage_5
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_5.order_by_modified
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_5.order_by_modified 
        end
    end

    def stage_6
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_6.order_by_test
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_6.order_by_test 
        end
    end

    def stage_7
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_7.order_by_test
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_7.order_by_test 
        end
    end

    def stage_8
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_8.order_by_modified_desc
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_8.order_by_modified_desc 
        end
    end

    def stage_9
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_9.order_by_modified_desc
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_9.order_by_modified_desc 
        end
    end

    def stage_10
        if is_agent?
            @candidates = Candidate.agent(session[:user_id]).stage_10.order_by_modified_desc
        else 
            @candidates = Candidate.recruiter(session[:user_id]).stage_10.order_by_modified_desc 
        end
    end


end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/stage_1.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 1:</strong> Candidate has shown interest</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Created On</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.created_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_10.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 10:</strong> Archived - No Contact</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_2.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 2:</strong> Candidate Interview Set with Agent</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Interview On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.interview_date %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_3.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 3:</strong> Affidavit sent to Candidate</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_4.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 4:</strong> Study Course Voucher Sent to Candidate</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_5.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 5:</strong> Studying for Test</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_6.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 6:</strong> Test Scheduled</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Test On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.test_date %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_7.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 7:</strong> Test Passed and Sent to Contracting</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Test Passed</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.test_date %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_8.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 8:</strong> Hired and Contracting Complete</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/stages/stage_9.html.erb
<div class="col-md-8 col-xl-9">
    <div class="row">
        <div class="col-12">
            <div class="shadow card mt-5 mb-5">
                <h5 class="card-header"><strong class="text-primary">Stage 9:</strong> Archived - Candidate No Longer Interested</h5>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Updated On</th>
                                        <th>Agent</th>
                                        <th>Recruiter</th>
                                        <th>Edit</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @candidates.each do |candidate| %>
                                    <tr>
                                        <td><%= candidate.first_name %> <%= candidate.last_name %></td>
                                        <td><%= candidate.updated_at.strftime("%b %d, %Y") %></td>
                                        <td><%= candidate.agent.first_name %> <%= candidate.agent.last_name %></td>
                                        <td><%= candidate.recruiter.first_name %> <%= candidate.recruiter.last_name %></td>
                                        <td><%= link_to "Edit", edit_candidate_path(candidate), :class => "badge badge-pill badge-warning" %></td>
                                        <td><%= link_to "View", candidate_path(candidate), :class => "badge badge-pill badge-info" %></td>
                                    </tr>
                                <% end %>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>