config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/login', to: 'user/sessions#new'
  post '/login', to: 'user/sessions#create'

  get '/logout', to: 'user/sessions#destroy'

  get '/stage_1', to: 'stages#stage_1'
  get '/stage_2', to: 'stages#stage_2'
  get '/stage_3', to: 'stages#stage_3'
  get '/stage_4', to: 'stages#stage_4'
  get '/stage_5', to: 'stages#stage_5'
  get '/stage_6', to: 'stages#stage_6'
  get '/stage_7', to: 'stages#stage_7'
  get '/stage_8', to: 'stages#stage_8'
  get '/stage_9', to: 'stages#stage_9'
  get '/stage_10', to: 'stages#stage_10'

  # namespace :user do 
  #   resources :agents, :recruiters, only: [:index, :new, :create, :show, :edit, :update]
  # end

  get '/auth/facebook/callback' => 'user/sessions#facebook'

  scope '/user' do 
    resources :agents, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
    resources :recruiters, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
  end 

  resources :candidates, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/recruiter.rb
class Recruiter < User
    has_many :candidates, :foreign_key => :recruiter_id 
    has_many :agents, :through => :candidates
    # Recruiter.new would save to the User table with a type of 'Recruiter'

end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
    before_action :find_recruiter, only: [:index, :show, :edit, :update]
    skip_before_action :redirect_if_not_authenticated, only: [:new, :create]
    layout "sidebar"
    
    def index
        @candidates = @recruiter.candidates
    end
    
    def new
        @recruiter = Recruiter.new
        render :layout => "application"
    end 

    def create
        @recruiter = Recruiter.create(recruiter_params)

        if @recruiter.save 
            session[:user_id] = @recruiter.id 
            redirect_to recruiter_path(@recruiter)
        else 
            render 'recruiters/new', :layout => "application"
        end

    end 

    def show
    end 

    def edit 
    end 

    def update
        @recruiter.update(recruiter_params)
        
        if @recruiter.save 
            redirect_to recruiter_path(@recruiter)
        else 
            render :edit 
        end
    end 

# --------------------------PRIVATE METHODS---------------------------------------

    private 

    def recruiter_params 
        params.require(:recruiter).permit(:first_name, :last_name, :phone_number, :email, :password)
    end 

    def find_recruiter
        @recruiter = User.find_by(id: session[:user_id])
    end

end

app/controllers/user/recruiters_controller.rb
class User::RecruitersController < ApplicationController
    before_action :find_recruiter, only: [:index, :show, :edit, :update]
    skip_before_action :redirect_if_not_authenticated, only: [:new, :create]
    
    def index
        @candidates = @recruiter.candidates
    end
    
    def new
        @recruiter = Recruiter.new
    end 

    def create
        @recruiter = Recruiter.create(recruiter_params)

        if @recruiter.save 
            session[:user_id] = @recruiter.id 
            redirect_to recruiter_path(@recruiter)
        else 
            render 'user/recruiters/new'
        end

    end 

    def show
    end 

    def edit 
    end 

    def update
        @recruiter.update(recruiter_params)
        redirect_to recruiter_path(@recruiter)
    end 

# --------------------------PRIVATE METHODS---------------------------------------

    private 

    def recruiter_params 
        pararms.require(:recruiter).permit(:first_name, :last_name, :phone_number, :email, :password)
    end 

    def find_recruiter
        @recruiter = Recruiter.find_by(id: params[:id])
    end

end

app/views/recruiters/edit.html.erb
<div class="col-6 offset-1 mt-5">
    <div class="shadow card">
        <h5 class="card-header text-center">Edit <%= current_user.first_name %> <%= current_user.last_name %></h5>
        <div class="card-body">
            <p class="card-text">
                <%= render 'partials/recruiter_form' %>
            </p>
        </div>
    </div>
</div>

app/views/recruiters/new.html.erb
<div class="col-4 mt-5">
    <div class="shadow card mb-5">
        <h5 class="card-header text-center">Recruiter Signup</h5>
        <div class="card-body">
            <p class="card-text">
                <%= render 'partials/recruiter_form' %>
            </p>
            <p class="card-text">
                <%= link_to '/auth/facebook?state=Recruiter' do %>
                    <button class="btn btn-outline-success btn-block">
                        <i class="fab fa-facebook text-decoration-none"> &nbsp;Signup with Facebook </i> 
                    </button>
                <% end %>
            </p>
        </div>
    </div>
</div>

app/views/recruiters/show.html.erb
<div class="col-md-4 col-xl-5 offset-md-2 offset-xl-2 align-self-center">
    <div class="shadow card text-center">
        <h5 class="card-header"><%= @recruiter.first_name %> <%= @recruiter.last_name %></h5>
        <div class="card-body">
            <p class="card-text">
                Phone: <%= @recruiter.phone_number %><br>
                Email: <%= @recruiter.email %>
            </p>
            <%= link_to "Edit Profile", edit_recruiter_path, :class => "btn btn-primary" %>
        </div>
    </div>
</div>