config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/login', to: 'user/sessions#new'
  post '/login', to: 'user/sessions#create'

  get '/logout', to: 'user/sessions#destroy'

  get '/stage_1', to: 'stages#stage_1'
  get '/stage_2', to: 'stages#stage_2'
  get '/stage_3', to: 'stages#stage_3'
  get '/stage_4', to: 'stages#stage_4'
  get '/stage_5', to: 'stages#stage_5'
  get '/stage_6', to: 'stages#stage_6'
  get '/stage_7', to: 'stages#stage_7'
  get '/stage_8', to: 'stages#stage_8'
  get '/stage_9', to: 'stages#stage_9'
  get '/stage_10', to: 'stages#stage_10'

  # namespace :user do 
  #   resources :agents, :recruiters, only: [:index, :new, :create, :show, :edit, :update]
  # end

  get '/auth/facebook/callback' => 'user/sessions#facebook'

  scope '/user' do 
    resources :agents, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
    resources :recruiters, only: [:new, :create, :show, :edit, :update] do
      resources :candidates, only: [:index, :new, :create]
    end
  end 

  resources :candidates, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitCrm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6396b028af.js" crossorigin="anonymous"></script>
  </head>

  <body class="mh-100 pb-0">
    <header class="shadow navbar navbar-light bg-white">
      <span class="navbar-brand mb-0 h1">Insurance Recruiter CRM</span>

      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Login", login_path, :class => "btn btn-info" %>
        </li>
      </ul>
    </header>
    
    <div class="container-fluid">
      <div class="row flex-xl-nowrap justify-content-center">
      
      <%= yield %>

      </div>
    </div>
    

  </body>
</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitCrm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6396b028af.js" crossorigin="anonymous"></script>
  </head>


    

  <body class="mh-100 pb-0">
    <header class="shadow navbar navbar-light bg-white">
      <span class="navbar-brand ml-auto mb-0 h1 text-primary">Insurance Recruiter CRM</span>
    </header>
    
    <div class="container-fluid flex-grow-1">
      <div class="row flex-xl-nowrap flex-grow-1">
        <div class="col-md-4 col-xl-3 bg-dark flex-grow-1">
          <nav class="bg-dark mx-1 flex-grow-1">
            <div class="container d-flex justify-content-center mt-2">
              <% if is_agent? %>
                <%= link_to "#{current_user.first_name} #{current_user.last_name}", agent_path(current_user), :class => "h3 text-white text-decoration-none" %><br>
              <% else %>
                <%= link_to "#{current_user.first_name} #{current_user.last_name}", recruiter_path(current_user), :class => "h3 text-light text-decoration-none" %>
              <% end %>
            </div>
            <div class="container d-flex justify-content-center">
              <%= link_to "Logout", logout_path, :class => "btn btn-outline-info btn-sm" %>
            </div>
            <div class="container d-flex justify-content-start mt-3">
              <h3 class="h4 text-light">Dashboard</h3>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <% if is_agent? %>
                <%= link_to "Dashboard", agent_candidates_path(session[:user_id]), :class => current_page?(agent_candidates_path(session[:user_id])) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
              <% else %>
                <%= link_to "Dashboard", recruiter_candidates_path(session[:user_id]), :class => current_page?(recruiter_candidates_path(session[:user_id])) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
              <% end %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
            <% if is_agent? %>
                <%= link_to "New Candidate", new_agent_candidate_path(session[:user_id]), :class => current_page?(new_agent_candidate_path(session[:user_id])) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
              <% else %>
                <%= link_to "New Candidate", new_recruiter_candidate_path(session[:user_id]), :class => current_page?(new_recruiter_candidate_path(session[:user_id])) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
              <% end %>
            </div>
            <div class="container d-flex justify-content-start mt-3">
              <h3 class="h4 text-light text-decoration-none">Stages</h3>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 1", stage_1_path, :class => current_page?(stage_1_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 2", stage_2_path, :class => current_page?(stage_2_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 3", stage_3_path, :class => current_page?(stage_3_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 4", stage_4_path, :class => current_page?(stage_4_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 5", stage_5_path, :class => current_page?(stage_5_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 6", stage_6_path, :class => current_page?(stage_6_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 7", stage_7_path, :class => current_page?(stage_7_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 8", stage_8_path, :class => current_page?(stage_8_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3">
              <%= link_to "Stage 9", stage_9_path, :class => current_page?(stage_9_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
            <div class="container d-flex justify-content-start ml-3 pb-2">
              <%= link_to "Stage 10", stage_10_path, :class => current_page?(stage_10_path) ? "h5 text-info text-decoration-none" : "h5 text-secondary text-decoration-none" %>
            </div>
          </nav>
        </div>

        <%= yield %>

      </div>
    </div>

  </body>
</html>